### PR TITLE
Add Robin Sloan article to the catalog

### PR DESCRIPTION
**Pull request by akkartik**

### CODE REVIEW

**Review by jryans — APPROVED** [review]
Thanks for the contribution, this looks great! 😄 

We could either merge as-is, or if you like, you could add the "related to" text in the free-form `description` field (which accepts Markdown).

**Comment by akkartik** [comment]
Yeah, I'll update the description.

**Comment by akkartik** [comment]
I love the deploy preview! Ok, how's this?

**Review by jryans — APPROVED** [review]
This looks great to me! 😄 Thanks again for the contribution.

**Pull request merged**
