### PR TITLE
Add Emacs to the catalog

### PR DESCRIPTION
**Pull request by khinsen**
As far as I can tell, Emacs is the oldest and by far the most widely used system that fulfills the criteria of the mission statement. Although it is showing its age, in particular in the lack of graphics support, I think it is an important example that everyone interested in malleable systems should study as an example of long-term success.

### CODE REVIEW

**Comment by jryans** [comment]
Ah yes, Emacs is a good addition and an interesting point on the spectrum. It seems to transcend far beyond "just" editing, with many interesting workflows and customisation paths. 

You would still need a fair bit of expert knowledge to customise it, so probably not something I'd consider generally accessible, but modern systems also have trouble with this.

As you say, a good example to learn from. Thanks for the contribution! 😄

**Comment by khinsen** [comment]
I guess I should write a blog post about the lessons to learn from Emacs for future malleable systems... it's on my to-do list!

**Comment by jryans** [comment]
Yes, that would be great! 😄 I'd be happy to have such a post on the site blog, if you're interested in that. Another option would be to syndicate it here if you want to post to your personal site as well as having it appear here.

**Comment by khinsen** [comment]
@jryans Here is a draft: https://gist.github.com/khinsen/0dc84b70c08296785d0c8133dce8a8ed. Does that look appropriate for your blog? I'd then put a short post on my own blog with a pointer plus a short motivation.

**Comment by jryans** [comment]
> Here is a draft: https://gist.github.com/khinsen/0dc84b70c08296785d0c8133dce8a8ed. Does that look appropriate for your blog? I'd then put a short post on my own blog with a pointer plus a short motivation.

Wow, this is a great post, and I'd love to have it on the site. 😁 I was hoping for people to contribute exactly these kinds of perspectives on malleability (both in various systems and about the principles generally), so this is great to see.

Shall I transform it into a new pull request here that we can use to preview it on the site, work out timing details, etc.? Or if you're motivated to create the PR as well, you could duplicate something like https://github.com/malleable-systems/malleable.systems/blob/master/content/blog/wildcard-review.md and tweak for your post. I'm happy to do it though, so just let me know what you'd prefer. 😄

**Comment by khinsen** [comment]
Pull request done: https://github.com/malleable-systems/malleable.systems/pull/11

**Pull request merged**
